apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: mmmihaeel/node-tasks-microservice:latest
          resources:
            limits:
              memory: 1512Mi
              cpu: "12"
            requests:
              memory: 1256Mi
              cpu: "0.5"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: microservices-config
                optional: true
          ports:
            - containerPort: 1779
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      imagePullSecrets:
        - name: dockerhub-credentials
